# Generated by Django 4.2.5 on 2023-10-03 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postagem",
            options={
                "ordering": ["-data_publicacao"],
                "verbose_name_plural": "Postagens",
            },
        ),
    ]
