# Generated by Django 4.2.5 on 2023-10-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autor", "0001_initial"),
        ("blog", "0002_alter_postagem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="autor.autor"
            ),
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
