# Generated by Django 4.2.5 on 2023-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_postagem_autor_delete_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
    ]
