# Generated by Django 4.2.5 on 2023-10-03 19:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_postagem_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="conteudo",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
