# Generated by Django 4.2.5 on 2023-10-11 21:56

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_postagem_conteudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postagem",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postagem",
            name="conteudo",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
