# Generated by Django 4.2.5 on 2023-11-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_categoria_slug_postagem_slug_alter_postagem_conteudo"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
